dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - cd decide
  - python manage.py test census --keepdb
notifications:
 email:  
    on_success: always
    on_failure: always
deploy:
   provider: heroku
   app: egc-app-decide-prod
   strategy: git
   api_key: 
     secure: $HEROKU_TOKEN
